name: EonCore
version: 1.0
main: me.squid.eoncore.EonCore
api-version: 1.15
authors: [Squid]
description: Epic description
commands:
  gmc:
    permission: eoncommands.gmc
    description: Sets gamemode to creative
  gms:
    permission: eoncommands.gms
    description: Sets gamemode to survival
  gmsp:
    permission: eoncommands.gmsp
    description: Sets gamemode to spectator
  feed:
    permission: eoncommands.feed
    description: Feed people or yourself
  heal:
    permission: eoncommands.heal
    description: Feed and heal yourself
  anvil:
    permission: eoncommands.anvil
    description: Portable anvil
  enderchest:
    permission: eoncommands.enderchest
    description: Portable ender chest
    aliases: [ec]
  clearinventory:
    permission: eoncommands.clearinventory
    description: Clears the inventory
    aliases: [ci]
  burn:
    permission: eoncommands.burn
    description: Burn people lol
  extinguish:
    permission: eoncommands.extinguish
    description: Sets out the fire
  admin:
    permission: eoncommands.admin
    description: Opens the Admin GUI
  vanish:
    permission: eoncommands.vanish
    description: Vanish from people
  discord:
    description: Shows the server discord
  disposal:
    description: Dispose of unneccasary items
    aliases: [trash]
  nightvision:
    permission: eoncommands.nightvision
    description: Grants infinite night vision without particles
    aliases: [inv]
  f:
    permission: eoncommands.f
    description: F in the chat
    aliases: [finchat]
  gamemodecheck:
    permission: eoncommands.gamemodecheck
    description: Sends back the gamemode of a player
    aliases: [gmcheck]
  pickup:
    permission: eoncommands.pickup
    description: Sets the pickup
  invsee:
    permission: eoncommands.invsee
    description: Look into another player's inventory
  fly:
    permission: eoncommands.fly
    description: Toggles fly
  commandspy:
    permission: eoncommands.commandspy
    description: Toggle seeing people's commands
  freeze:
    permission: eoncommands.freeze
    description: Freeze players in place
  shop:
    description: Opens the Main Shop Menu
    aliases: [servershop]
